[build]
builder = "NIXPACKS"
buildCommand = "npm install && npm run build -w @mk/web"

[deploy]
startCommand = "npm run start -w @mk/web"
healthcheckPath = "/login"
healthcheckTimeout = 120
restartPolicyType = "ON_FAILURE"
